# Generated by Django 3.0.5 on 2020-04-13 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200414_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='may_extend',
            field=models.BooleanField(default=False, verbose_name='Возможность продлить'),
        ),
        migrations.AlterField(
            model_name='product',
            name='buyback_date',
            field=models.DateField(verbose_name='Ожидаемоая дата выкупа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='check_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Check', verbose_name='Номер чека'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.BooleanField(default=False, verbose_name='Топ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='products', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.IntegerField(verbose_name='Цена выплаты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.IntegerField(verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, 'В ожидании выкупа'), (1, 'В продаже'), (3, 'Продано'), (4, 'Выкуплено')], default=0, verbose_name='Статус'),
        ),
    ]
