# Generated by Django 3.0.5 on 2020-04-14 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200415_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='may_extend',
        ),
    ]
